### ISSUE TITLE
Is it possible to append a PDF from memory?

### ISSUE THREAD

**Issue by joshfoskett** [chunyenHuang/hummusRecipe#126]
Similar question to #68.

Essentially, all of our files are hosted on S3, so ideally I'd like to just fetch the body of each PDF, which is represented as a `Buffer`, and use that instead of storing it on the server, providing a path, and then deleting it afterwards. It works fine when instantiating `new HummasRecipe(pdfBuffer)`. However, `recipe.appendPage(pdfBuffer)` results in:
```
TypeError: Unable to start parsing PDF file
    at Recipe.appendPage (/.../node_modules/hummus-recipe/lib/appendPage.js:16:30)
    at additionalPages.forEach (/.../mytribus-server/start/routes.js:45:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Looking through the source code, I noticed that [Recipe.js](https://github.com/chunyenHuang/hummusRecipe/blob/master/lib/Recipe.js#L129) wrapped the `Buffer` with `hummus.PDFRStreamForBuffer`, and passed it to `hummus.createReader`, which [`appendPage.js`](https://github.com/chunyenHuang/hummusRecipe/blob/master/lib/appendPage.js#L16) also does. However, I then get:
```
TypeError: unable to create copying context. verify that the target is an existing PDF file
    at Object.appendPDFPagesFromPDFWithAnnotations (/.../node_modules/hummus-recipe/lib/utils.js:41:30)
    at Recipe.appendPage (/.../node_modules/hummus-recipe/lib/appendPage.js:42:21)
    at additionalPages.forEach (/.../start/routes.js:45:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

If I store the file locally, and reference its path, it works as expected.

**Comment by thebenlamm** [comment]
I ran into this issue today and this is what I've got to contribute.

First off I commented out lines 16 through 36 in `appendPage.js`. I only have one page in my pdf so didn't want to bother with createReader which is only used to get the page count.

So now it's throwing on `appendPage.js` line 42 on `hummusUtils.appendPDFPagesFromPDFWithAnnotations()`.

`utils.appendPDFPagesFromPDFWithAnnotations()` calls `pdfWriter.createPDFCopyingContext()`.
(Incidentally, according do HummusJS [tests](https://github.com/galkahana/HummusJS/blob/b699d6a01ba027428120cbe5b1c16813bed0521d/tests/StreamCopyingContext.js) this exact scenario should work.)

[`createPDFCopyingContext()`](https://github.com/galkahana/HummusJS/blob/457f273a5886342ecd6613e12bc3baf5d8e25ce6/src/PDFWriterDriver.cpp#L1068) is c++ code and is where the error

     unable to create copying context. verify that the target is an existing PDF file
is thrown from, apparently because the `copyingContext` is not set. I'm not so familiar with c++ but it seems the issue is on [line 1111](https://github.com/galkahana/HummusJS/blob/457f273a5886342ecd6613e12bc3baf5d8e25ce6/src/PDFWriterDriver.cpp#L1111) where my best guess is the proxy isn't being set correctly.

**Comment by saulodecarlo** [comment]
Recipe.js Line 238: Feature: Inserting Pages is not supported in Buffer Mode yet.
Josh, I start work with buffer, but my problem is with large files it consumes too much memory and generates this error: 
> Allocation failed - JavaScript heap out of memory

My files are hosted on S3 too. I can't delete the file afterwards. Do you have this problem?
Similar question #125
