### ISSUE TITLE
Cannot find module PDFWStreamForBuffer

### ISSUE THREAD

**Issue by jaffarc** [chunyenHuang/hummusRecipe#138]
Error: Cannot find module './PDFWStreamForBuffer'
No hummus.js file failed to remove or add import file

`hummus.PDFWStreamForBuffer = require('./PDFWStreamForBuffer');`

Erro: 

> Error: Cannot find module './PDFWStreamForBuffer'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/var/www/api-nodejs/node_modules/hummus/hummus.js:31:30)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/var/www/api-nodejs/node_modules/hummus-recipe/lib/Recipe.js:1:16)

**Comment by lucasapereira** [comment]
Same problem here

internal/modules/cjs/loader.js:670
    throw err;
    ^

Error: Cannot find module './PDFWStreamForBuffer'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/home/lucas/cerberus-jwt/node_modules/hummus/hummus.js:31:30)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)

**Comment by chunyenHuang** [comment]
https://github.com/galkahana/HummusJS/pull/386/files
