### ISSUE TITLE
Overlay PDF to all pages

### ISSUE THREAD

**Issue by AndreHermanto** [chunyenHuang/hummusRecipe#174]
Hi HummusRecipe team,

I'm having trouble trying to make PDF overlay work. I got an error of 

`(node:31031) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property `width` of 'undefined' or 'null'.
    at Recipe.overlay (/Users/andre/Documents/auth0-rems/node_modules/hummus-recipe/lib/overlay.js:29:11)
    at /Users/andre/Documents/auth0-rems/routes/auth0-rems.js:38:10
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
(node:31031) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:31031) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero`

```
		const pdfDoc = new HummusRecipe('./doc.pdf', 'finalDoc.pdf');

		pdfDoc.overlay('./output.pdf')
			.endPDF(() => {
				console.log("FINISH!");
			})
```

I want to overlay 1 pdf page as a watermark/stamp on all pages in a document. 

I guess this works, but is there anyway I can overlay to all pages?

```
		pdfDoc.editPage(1)
			.overlay('./output.pdf')
			.endPage()
			.endPDF(() => {
				console.log("FINISH");
			})
```

**Comment by AndreHermanto** [comment]
I found a solution by using PDF metadata to get the document pages:

`		const pdfDoc = new HummusRecipe('./doc.pdf', 'finalDoc.pdf');

		let pageNo = 1;
		while(pageNo <= pdfDoc.metadata.pages){
			pdfDoc.editPage(pageNo)
			.overlay('./output.pdf')
			.endPage()

			pageNo++;
		}


		pdfDoc.endPDF(() => {
				console.log("FINISH");
		})`

I hope it can help others
