### ISSUE TITLE
TypeError: Unable to end PDF

### ISSUE THREAD

**Issue by christiansaiki** [chunyenHuang/hummusRecipe#35]
Here is my code
```javascript
const pdfDoc = new HummusRecipe('output.pdf', 'output2.pdf')
  pdfDoc
    // edit 1st page
    .editPage(1)
    .text('Add some texts to an existing pdf file', 50, 50)
    // end and save
    .endPDF();
```

Here is the error log
```
TypeError: Unable to end PDF
    at Recipe.endPDF (/Users/chris/development/theVelops/solstar-api/node_modules/hummus-recipe/lib/Recipe.js:173:21)
    at addContractIdInPdf (/Users/chris/development/theVelops/solstar-api/functions/insertContractIdInPdf.js:19:6)
    at Object.<anonymous> (/Users/chris/development/theVelops/solstar-api/functions/insertContractIdInPdf.js:24:1)
    at Module._compile (module.js:635:30)
    at loader (/Users/chris/.nvm/versions/node/v8.9.2/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/chris/.nvm/versions/node/v8.9.2/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
```

What am I doing wrong?

**Comment by chunyenHuang** [comment]
Can you try with `endPage`

```javascript
const pdfDoc = new HummusRecipe('output.pdf', 'output2.pdf')
  pdfDoc
    .editPage(1)
    .text('Add some texts to an existing pdf file', 50, 50)
    .endPage()
    .endPDF();

```

**Comment by nikkimandhani** [comment]
Getting same error even after endPage();  can someone please help me in solving issue

**Comment by chunyenHuang** [comment]
@nikkimandhani Can you post your code here?

**Comment by nikkimandhani** [comment]
Here is code..

const HummusRecipe = require('hummus-recipe');
const pdfDoc = new HummusRecipe('login.pdf', 'output.pdf');
pdfDoc
    .editPage(1)
    .text('Add some texts to an existing pdf file', 150, 300)
    .rectangle(20, 20, 40, 100)
    .comment('Add 1st comment annotaion', 200, 300)
    .image('/path/to/image.jpg', 20, 100, {width: 300, keepAspectRatio: true})
    .endPage()
    .endPDF();

Error...
TypeError: Unable to end PDF
    at Recipe.endPDF (/home/admins/node_modules/hummus-recipe/lib/Recipe.js:195:21)
    at Object.<anonymous> (/home/admins/Documents/pdf/pdfedit.js:11:6)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

**Comment by chunyenHuang** [comment]
is `login.pdf` the correct file path?

**Comment by nikkimandhani** [comment]
yeah..i have tried it with full path also...still facing the same error..

hummus-recipe/lib/Recipe.js:195
        this.writer.end();
type error...

**Comment by akky** [comment]
I had the exact same error with the same code (I guess it is from README's modify sample code), and the error was solved when I changed '/path/to/image.jpg' with an existing image file.

The error message would have room to be improved.

**Comment by PatrikAarnivaara** [comment]
> 

I am also getting this error. Did you solve the problem?
